name: pushing to aws eks

## Events in which job will get trigger
on:
 push:
  branches:
   - main

## Job section

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Echo
      run: |
            echo "hello world"
            echo $USER
    - uses: actions/checkout@v2 
    - name: Login to Docker Hubxs
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: build image from docker file
      run: |
            cd docker
            docker build -t myimg .
            docker tag myimg kamal1109/casbin:myimg
            docker push kamal1109/casbin:myimg
    # - name: Deploy in EC2
    #   env:
    #       PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
    #       HOSTNAME : ${{ secrets.HOSTNAME  }}
    #       USER_NAME : ${{ secrets.USER_NAME  }}
          
    #   run: |
    #     echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
    #     ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} 
    #     echo "test "
    #     cat file1.txt     
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          whoami 
          echo $USER
          if [ -d "cicd" ]
          then
          rm -rf cicd
          git clone https://github.com/kamal-devtron/cicd.git
          cd cicd
          cat install.sh
          echo "me"
          else
          git clone https://github.com/kamal-devtron/cicd.git
          cd cicd
          chmod 700 install.sh && ./install.sh
          microk8s config view > kubeconfig
          export KUBECONFIG=kubeconfig
          fi
          microk8s kubectl apply -f pod.yaml