name: pushing to aws eks

## Events in which job will get trigger
on:
 push:
  branches:
   - main

## Job section

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - run: |
          echo "hello world"
    - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

          mkdir kamal
          cd kamal
          touch testing      